apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mosquitto-hpa
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mosquitto-deployment
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.memoryUtilization }}
  behavior:                               #spec scale down rapide
    scaleDown:
      stabilizationWindowSeconds: 20      #taille cache garde toute les analyse moins vielle que x sec
      policies:
      - type: Pods
        value: 1                          
        periodSeconds: 5                  #timing entre les analyse sys
    scaleUp:                              #spec scale up rapide
      stabilizationWindowSeconds: 10      
      policies:
      - type: Pods
        value: 2                          
        periodSeconds: 2