apiVersion: v1
kind: Service
metadata:
  name: mosquitto-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mosquitto
  type: {{ .Values.service.type }}
  ports:
    - name: mqtt
      port: {{ .Values.service.mqttPort }}
      targetPort: {{ .Values.service.mqttPort }}