image:
  repository: eclipse-mosquitto
  tag: "2.0"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

service:
  type: ClusterIP
  mqttPort: 1883

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 70

mosquitto:
  allowAnonymous: true
  persistence: false