all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    NCC:
      hosts: 
      children:
        HA:
          hosts:
            haproxy:
              ansible_host: 172.31.250.254
        K8S:
          hosts:
            master01:
              ansible_host: 172.31.250.187
            master02:
              ansible_host: 172.31.250.115
            worker01:
              ansible_host: 172.31.250.128
            worker02:
              ansible_host: 172.31.250.154
        PG:
          hosts:
    PIP:
      hosts:
    SEC:
      hosts:
    COM:
      hosts:
        reverseproxy:
          ansible_host: 172.31.250.163
        test:
          ansible_host: 172.31.252.31
        front:
          ansible_host: 172.31.252.65