#just for tac
statistics=true
job=Gold_Stockage
jobVersion=0.1
date=2026-02-27 010155400
contextName=Default
jobId=_FbB6UBNzEfGop4mQTAFkTg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=GOLDPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=