server {
        listen 8080;
        server_name 172.31.252.204;
        ## Redirige le HTTP vers le HTTPS ##
        return 301 https://$server_name:8443$request_uri;
}

server {
    listen 8443 ssl;

    server_name 172.31.252.204;                                           #ip à redistribuer

    location = / {
        return 302 /auth/login?next=http://172.31.249.231:8080/;
    }

    ssl_certificate     /etc/nginx/ssl/certs/airflow.crt;
    ssl_certificate_key /etc/nginx/ssl/private/airflow.key;

    location / {
        proxy_pass http://172.31.249.231:8080/;                         #ip destination
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}