upstream cockpit_backend {
    ip_hash;  # sticky session : même client -> même backend
    server 172.31.253.89:5000 max_fails=3 fail_timeout=30s;
}

# Mapping IP backend -> label pour les logs
map $upstream_addr $backend_label {
    ~^172\.31\.253\.89:5000 cockpit_backend1;
    default                   unknown;
}


map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

log_format cockpit_log '$remote_addr [$time_local] '
                        '"$request" $status '
                        'backend=$backend_label '
                        'addr=$upstream_addr '
                        'rt=$request_time';

server {
    listen 5000;
    server_name 172.31.252.204;

    access_log /var/log/nginx/cockpit.log cockpit_log;
    error_log  /var/log/nginx/cockpit_error.log warn;

    location / {
        proxy_pass         http://cockpit_backend;
        proxy_http_version 1.1;

        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host            $host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_connect_timeout 10s;

        proxy_buffering off;
    }
}