server {
        listen 80;
        server_name 172.31.252.204;
        ## Redirige le HTTP vers le HTTPS ##
        return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;

    server_name 172.31.252.204;                                           #ip à redistribuer

    ssl_certificate     /etc/nginx/ssl/certs/front.crt;
    ssl_certificate_key /etc/nginx/ssl/private/front.key;

    location / {
        proxy_pass http://172.31.250.120:80/;                           #ip destination
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}