server {
    listen 80;

    server_name 172.31.240.6;                                           #ip à redistribuer
    location / {
        proxy_pass http://172.31.250.120:80/;                           #ip destination
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}