#just for tac
statistics=true
job=BronzeJob_Stockage
jobVersion=0.1
date=2026-02-27 011422832
contextName=Default
jobId=_w0XHYBNpEfGop4mQTAFkTg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=GOLDPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=