#just for tac
statistics=true
job=SilverJob
jobVersion=0.1
date=2026-02-23 172125198
contextName=Default
jobId=_PfUbcMwyEfCmIN2e1Pblfg
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=GOLDPROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=